name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      TIMESTAMP_TAG: ${{ github.run_id }}  # or use `date +%s` in a run step and export if needed

    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mamok/tests:${TIMESTAMP_TAG}

      - name: Push Docker image
        run: docker push mamok/tests:${TIMESTAMP_TAG}
